export enum SLIDER {
  SLIDER_SHOW = 'SLIDER_SHOW',
  SLIDER_HIDE = 'SLIDER_HIDE'
}

export enum WORKFLOW {
  WORKFLOW_NEXT = 'WORKFLOW_NEXT',
  WORKFLOW_PREV = 'WORKFLOW_PREV'
}


export type EVENT_TYPES = SLIDER | WORKFLOW;
